### PR TITLE
Use array syntax short to improve readability

### PR DESCRIPTION
**Pull request by shakaran**
Code improvement using php-cs-fixer as:

    php php-cs-fixer fix --rules='{"array_syntax": {"syntax": "short"}}' ps_viewedproduct

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @shakaran 
Thank you for your PR but according ours  [coding standard](http://build.prestashop.com/news/prestashop-coding-standards/#php), i'm closing this one.

Regards

**Comment by shakaran** [comment]
@aleeks let me know if I am wrong, but the PS coding standard and symfony standards don't say anything about use array() or []. In fact, they are probably showing array() because the docs are written time ago in old PHP 5.3 syntax when [] doesn't even exist. 

You should notice that mostly all people written new code (in Symfony or PHP) is deprecating the lossy way to write array(), specially for big config arrays.

**Comment by aleeks** [comment]
@maximebiloe WDYT ?

**Comment by maximebiloe** [comment]
@shakaran when we updated our coding standards last year, Symfony was using the long array syntax for 5.3 compatibility (even if it was not clearly defined). So, to keep consistency we decided to **not** use the short hand syntax.
So, while we're not changing our standards for now, let's keep using the long array syntax.

**Comment by shakaran** [comment]
@maximebiloe which sense has support a PHP versions which are currently EOL? I mean if the PHP world deprecate a old version, without security fixes, should symfony or PS world give support? Big projects should give example and recommend always better versions. PHP 5.3 should be unsupported, also 5.4 and 5.5 for the sake of good progress technology. http://php.net/supported-versions.php if big projects dont' sum forces, the php usage will take years and years to take new php versions. We still didn't learn about the past with 4.4 and 5.1/5.2 versions.

**Comment by maximebiloe** [comment]
We support PHP 5.4 for hosting constraints. When we launched 1.7 version a lot of new install were made on PHP 5.4 as many hosting providers do not provide something else by default.

**Comment by shakaran** [comment]
@maximebiloe make consistency in arrays will take only some seconds (using the php-cs-fixer over each repo), even you can add a .php_cs config file in repo that would be run ad pre-hook in pull request. If you are already using at least 5.4 as contraint, it doesn't should give problems of support. That old hostings supporting 5.4 probably are cpanels, but cPanel already launch a "MultiPHP" feature for easy change between versions (from 5.3 to 7.1), which should be a lot easy for sysadmins or even users switch to that. Like I am purposing is that you "relax" the coding standard to support [] and array() for the moment, and recommend use [] preferably, and for example for 1.8, use only 5.5 or 5.6 and recommend only use [] format preferably. That should help to make a better php world in best practices

**Pull request closed without merging**
